### ISSUE TITLE
Cannot create any file

### ISSUE THREAD

**Issue by jdleung** [PHPOffice/PHPPresentation#163]
Installed the probject without composer, I kept getting errors until I blind the following line in Sample_Header.php
// require_once **DIR** . '/../vendor/autoload.php';

But still the script "simple sample" cannot create any file. It ended at:
11:59:52 Create new PHPPresentation object
11:59:52 Set properties
11:59:52 Create slide
11:59:52 Create a shape (drawing)
11:59:52 Create a shape (rich text)

I had also tried to use to the sample codes in https://github.com/PHPOffice/PHPPresentation "Getting started" 

Error 500 again! Then I tried to echo something like this:
echo "top";
$currentSlide = $objPHPPowerPoint->getActiveSlide();
echo "bottom";

"top" is printed and "bottom" is not. I did not go further to check the code any more. Can anyone tell what's wrong there?

Thanks.

**Comment by Progi1984** [comment]
Which errors have you got ? Without errors, i can't help you.

**Comment by jdleung** [comment]
the browser shows error 500 which means Internal server error.

and when I use simple sample, it seems that it has not finish its job.

Is it a big difference between composer install and manual install?

Thanks.

**Comment by jdleung** [comment]
It's no problem on checking:
![a](https://cloud.githubusercontent.com/assets/486474/12252586/75790c56-b913-11e5-9fc2-cf2e9bee8b41.png)

It seems it did not finish its job to create a file
![b](https://cloud.githubusercontent.com/assets/486474/12252585/755e40ba-b913-11e5-8a54-4f6b1168fb98.png)

**Comment by Progi1984** [comment]
Normally, no difference. May be have you got some errors in your php_errors.log file ? or apache errors log ?

**Comment by jdleung** [comment]
I got this in php error log:
[12-Jan-2016 13:39:19 Europe/Berlin] PHP Fatal error:  Class 'PhpOffice\Common\XMLWriter' not found in /Applications/MAMP/htdocs/PHPPresentation-0.5.0/src/PhpPresentation/Writer/PowerPoint2007/AbstractPart.php on line 74

but I had check php info, xmlwrite is enabled.

what's wrong?

**Comment by Progi1984** [comment]
You have not included the code from https://github.com/PHPOffice/Common

**Comment by jdleung** [comment]
OK, it works after clear two errors below:

1. PHP Fatal error:  Class 'PhpPresentation' not found
There is only "use PhpOffice\PhpPresentation\PhpPowerpoint;" in the sample codes, so I have to replace it with "use PhpOffice\PhpPresentation\PhpPresentation;" to make it works.

2.Uncaught exception 'Exception' with message 'File ./resources/phppowerpoint_logo.gif not found!
I have to cancel to create a shape in sample codes to make it works

and it seems the document doesn't suggest to include common. 

Any way, it works now and get the job done very well. 

Thanks a lot.

**Comment by Progi1984** [comment]
@jdleung Normally, I corrected documentation & samples in latest version of the develop branch. Could you test it, please ?

**Comment by jdleung** [comment]
@Progi1984 OK, I will download it and have a try. ;-)

**Comment by jdleung** [comment]
It's great to see that the background can be set now! ;-), Must I the colors; COLOR_RED, COLOR_DARK...? when I try to use my own color like 'FF660000', it seems not work. 

And still for a beginner, like me, wants to run the script normally and goes into sample page without too much settings. By now, I need to do the following in Sample_Header.php for it's first running(manual install):
1. Add  \PhpOffice\PhpPresentation\Autoloader::register(); 
2. Blind // require_once __DIR__ . '/../vendor/autoload.php';
3. Download and include 'common' (how about bundle it into PHPPresentation download file), and add the following two lines
require_once 'Common-develop/src/Common/Autoloader.php';
\PhpOffice\Common\Autoloader::register();

Thanks!

**Comment by Progi1984** [comment]
For Color, try this :

(Sample : Sample_15_Background.php)
```php
$oColor = new StyleColor();
$oColor->setARGB('FF660000');

$oBkgColor = new Color();
$oBkgColor->setColor($oColor);
$oSlide1->setBackground($oBkgColor);
```

For installing, I will update the documentation.

**Comment by alexscloh** [comment]
![capture](https://cloud.githubusercontent.com/assets/4832792/15922130/c4b914cc-2e58-11e6-90e8-e8b15f5b0557.JPG)

I already have phpoffice common but i still unable to write file

**Comment by alexscloh** [comment]
It's been few days from my last post, no one able to help me solving issue?

**Comment by dulara1994** [comment]
jdleung how did you overcome the uncaught exception error? please. explanation would be greatful.
Thanks!
